### ISSUE TITLE
Could we get a pair of environment variable to control what UID and GID the different services run as?

### ISSUE THREAD

**Issue by UntouchedWagons** [dbsentry/keyper-docker#2]
By default the nginx cert files are owned by root:root and the ldap stuff is owned by systemd-network:systemd-timesync (101:102) which makes storing persistent data outside of volumes a bit of a pain. It also complicates backups and external certificate management.

**Comment by mlgupta** [comment]
So, currently, both nginx (100:101 uid:gid) and openLDAP (101:102 uid:gid) runs as their respective users (i.e. as nginx and ldap). The name mismatch you are seeing is because of how uid:gid are mapped to the local system (podman seems to do a better job managing these than docker).

I did this to avoid too much customization. Do you think that it would make sense to run all the services as one user?

**Comment by UntouchedWagons** [comment]
They don't all have to be running under the same UID/GID, you could have NGINX-UID & NGINX-GID which defaults to 100:101, then a pair for ldap which defaults to 101:102.

I'm not gonna lie, those are some odd UID:GID combos.

**Comment by mlgupta** [comment]
I agree. Let me work on it.

As they stand, they seem default from alpine.

In any case, your suggestion is good. Let me work on it.

Thx

**Comment by mlgupta** [comment]
Added four environment variables: LDAP_UID, LDAP_GID, NGINX_UID, and NGINX_GID with default values of 10100, 10100, 10080, and 10080 respectively.
 
A new image was pushed to docker.
